// <auto-generated />
using System;
using Differ.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Differ.Infra.Data.Migrations
{
    [DbContext(typeof(DifferContext))]
    [Migration("20200708173323_Diff")]
    partial class Diff
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Differ.Domain.Models.Diff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LeftDiffData")
                        .HasColumnType("varchar(4000)");

                    b.Property<string>("RightDiffData")
                        .HasColumnType("varchar(4000)");

                    b.HasKey("Id");

                    b.ToTable("Diffs");
                });
#pragma warning restore 612, 618
        }
    }
}
